# Generated by Django 3.2 on 2021-05-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='completeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MONTH', models.CharField(max_length=80, null=True)),
                ('YEAR', models.IntegerField()),
                ('CA_NO', models.IntegerField()),
                ('MTR_NO', models.IntegerField()),
                ('ZONE_NAME', models.CharField(max_length=80, null=True)),
                ('REGION', models.CharField(max_length=80, null=True)),
                ('REGIO_GROUP', models.CharField(max_length=80, null=True)),
                ('ACC_CLASS', models.CharField(max_length=80, null=True)),
                ('SUB_DIVISION', models.CharField(max_length=80, null=True)),
                ('TAMPER_COUNT', models.IntegerField()),
                ('KWH', models.FloatField()),
                ('PAY_AGAINST_CURR_DMD', models.IntegerField()),
                ('PAY_AGAINST_ARREARS', models.IntegerField()),
                ('PAYMENT_AGAINSTTOTAL', models.IntegerField()),
                ('BUCKETING_DERIVED', models.CharField(max_length=80, null=True)),
                ('BUCKETING_DISPLAY', models.CharField(max_length=80, null=True)),
            ],
        ),
    ]
