# Generated by Django 3.2 on 2021-05-02 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lr_visual', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedata',
            old_name='PAYMENT_AGAINSTTOTAL',
            new_name='PAYMENT_AGAINST_TOTAL',
        ),
    ]
