# Generated by Django 3.2 on 2021-05-02 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lr_visual', '0002_rename_payment_againsttotal_completedata_payment_against_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedata',
            old_name='REGIO_GROUP',
            new_name='UNIT_CODE',
        ),
    ]
